spring:
  application:
    name: Customer-management-System

  datasource:
    url: jdbc:mysql://localhost:3306/customer_db?createDatabaseIfNotExist=true
    username: root
    password: Hasitha@8465

  jpa:
    hibernate:
      ddl-auto: create 
    sql-show: true


